### ISSUE TITLE
Problemas para Adicionar os campos de data na extensão Cycle Time.

### ISSUE THREAD

**Issue by begydio** [altamir-junior-dias/azure-devops-extension-cycle-time-histogram#1]
Bom dia Altamir, tudo bem ?

Instalei sua extensão em meu Azure DevOps Board e ao selecionar os campos de data "Cycle Time Start" e "Cycle Time End", não estão disponíveis as opções para seleção ? Sabe se existe algum fix para isso ?

A situação ocorre mesmo escolhendo queries padrão do Azure ou Queries customizadas como listar todas as Tasks de uma sprint atual.

Poderia me ajudar com esse caso, anexei uma imagem de como o 'list box' está sendo apresentado em minha tela.

![problemas para escolher campo de data](https://github.com/user-attachments/assets/6579bf19-8c01-442a-8027-59b26416a306)

**Comment by altamir-junior-dias** [comment]
Ola, isso acontece pelo fato de não ter colunas do tipo Date dentro da query.
